version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  web:
    build: .
    ports:
      - "3000:3000"
    links: 
      - mongo
    depends_on:
      - mongo
    command: node index.js
